name: Run Script
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Running Script
        run: ./scripts/testscript.sh HelloWorld