name: Run Script
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          # Navigate to the scripts folder and execute the script
          ./scripts/print-datetime.ps1